config/routes.rb
Betfair::Application.routes.draw do
  resources :simulations, only: [:new] do
    collection do
      post :run
    end
  end
  resources :market_filters

  match 'jobs/run', to: 'jobs#run', via: :get
  match 'jobs/load_event_types', to: 'jobs#load_event_types', via: :get
  match 'jobs/load_markets', to: 'jobs#load_markets', via: :get
  match 'jobs/update_markets', to: 'jobs#update_markets', via: :get
  match 'home', to: 'home#new', via: :get

  root 'simulations#new'

  #Authentication
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
end

app/models/simulation.rb
class Simulation
  attr_accessor :scenarios, :commission
  def initialize(commission)
    @commission = commission
    @scenarios = []
  end
end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController
  def new
    @venues = Venue.unique_filters
    @event_types = EventType.where("name like '%Racing'")
  end

  def run
    scenario = Scenario.new(params[:scenarios].symbolize_keys)
    simulation = Simulation.new(params[:commission].to_d)
    simulation.scenarios << scenario

    winnings_series = ['Winnings']
    summary_series = ['Summary']
    market_details = []
    total = 0

    market_filter.each_with_index do |market, index|
      amount = market.profit_loss(simulation)
      if amount != 0
        total += amount
        winnings_series << amount.round(2).to_f
        summary_series << total.round(2).to_f
        #market_details << market_detail(market, amount.round(2).to_f)
      end
    end
    render json: {chart_data: [winnings_series, summary_series], market_details: market_details}
  end

  private

  def market_filter
    markets = Market.joins(:event => :venue).closed
    markets = markets.where(['venues.territory= ?', params[:venue_territory]]) unless params[:venue_territory].blank?
    markets = markets.where(['venues.venue_class = ?', params[:venue_class]]) unless params[:venue_class].blank?
    markets = markets.where(['venues.tier = ?', params[:venue_tier]]) unless params[:venue_tier].blank?
    markets = markets.where(['venues.name = ?', params[:venue_name]]) unless params[:venue_name].blank?
    markets = markets.where(['events.event_type_id = ?', params[:event_type_id]]) unless params[:event_type_id].blank?
    markets = markets.where(['exchange_id = ?', params[:exchange_id]]) unless params[:exchange_id].blank?
    markets = markets.where(['start_time > ?', DateTime.strptime(params[:start_date], "%d/%m/%Y")]) unless params[:start_date].blank?
    markets = markets.market_type(params[:market_type]) unless params[:market_type].blank?
    markets
  end

  def venue_unique_values(field)
    Venue.uniq.pluck(field).compact.sort
  end

  def market_detail(market, profit_loss)
    {
      start_time: market.start_time.in_time_zone('Melbourne').strftime('%d-%m-%Y %H:%M:%S'),
            event_type: market.event.event_type.name,
            market_type: market.market_type,
            venue: market.event.venue.name,
            name: market.name,
            runners_summary: market.runners_sp_summary,
            amount: profit_loss
    }
  end
end

app/views/simulations/_form.html.erb
<%= form_tag(run_simulations_path, :remote => true, :id => 'simulationForm', class: 'form-horizontal', role: 'form') do%>
  <div id='simulation'>
  <div class="form-group">
    <label for="commission" class='col-md-2 control-label'>Commission</label>
    <div class='col-md-2'>
      <div class="input-group">
        <%= text_field_tag :commission, '5', class: 'form-control'%>
        <span class="input-group-addon">%</span>
      </div>
    </div>
  </div>
  <div class='col-md-12'>
    <h3>Market filter</h3>
  </div>
  <div class="form-group">
    <label for="event_type" class='col-md-2 control-label'>Market</label>
    <div class='col-md-2'>
      <%= select_tag "exchange_id", "<option value='2'>AUS</option><option value='1'>UK</option>".html_safe, class: 'form-control', prompt: 'Exchange'%>
    </div>
    <div class='col-md-2'>
      <%= select_tag "event_type_id", options_from_collection_for_select(@event_types, 'id', 'name'), class: 'form-control', prompt: 'Event Type'%>
    </div>
    <div class='col-md-2'>
      <%= select_tag "market_type", "<option>WIN</option><option>PLACE</option>".html_safe, class: 'form-control', prompt: 'Market Type'%>
    </div>
    <div class='col-md-2'>
      <div class="input-group date">
        <input type="text" name='start_date' class="form-control" placeholder="Start Date"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
      </div>
    </div>
  </div>
  <div class="form-group">
    <label for="venue" class='col-md-2 control-label'>Venue</label>
    <div class='col-md-2'>
      <%= select_tag "venue_territory", options_for_select(@venues[:territory]), class: 'form-control', prompt: 'Territory'%>
    </div>
    <div class='col-md-2'>
      <%= select_tag "venue_class", options_for_select(@venues[:venue_class]), class: 'form-control', prompt: 'Class'%>
    </div>
    <div class='col-md-2'>
      <%= select_tag "venue_tier", options_for_select(@venues[:tier]), class: 'form-control', prompt: 'Tier'%>
    </div>
    <div class='col-md-2'>
      <%= select_tag "venue_name", options_for_select(@venues[:name]), class: 'form-control', prompt: 'Name'%>
    </div>
  </div>
  <div class='col-md-12'>
    <h3>Runner filter</h3>
  </div>
  <% s = Scenario.new%>
  <%= fields_for :scenarios, s,  child_index: s.object_id  do |scenario| %>
    <div id='scenario'>
    <div class="form-group">
      <label for="market_type" class='col-md-2 control-label'>Position</label>
      <div class='col-md-2'>
        <%= scenario.text_field :position, class: 'form-control', placeholder: 'Comma Seperated'%>
      </div>
      <div class='col-md-2'>
        <%= select_tag "scenarios[range]", "<option>ALL</option><option>TOP 1/2</option><option>TOP 1/3</option><option>BOTTOM 1/2</option><option>BOTTOM 1/3</option>".html_safe, class: 'form-control', prompt: 'OR Range'%>
      </div>
       <div class='col-md-2'>
           <%= scenario.text_field :min_odds, class: 'form-control', placeholder: 'Min odds'%>
       </div>
       <div class='col-md-2'>
         <div class="input-group">
           <%= scenario.text_field :max_odds, class: 'form-control', placeholder: 'Max odds'%>
         </div>
       </div>
     </div>
    <div class="form-group">
      <label for="market_type"  class='col-md-2 control-label'>Bet</label>
      <div class='col-md-2'>
        <%= select_tag "scenarios[side]", "<option value='BACK'>BACK</option><option value='LAY'>LAY</option><option value='LAY (SP)'>LAY SP (max liability)</option>".html_safe, class: 'form-control', prompt: 'Bet type'%>
      </div>
      <div class='col-md-2'>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <%= scenario.text_field :size, class: 'form-control', placeholder: 'Size',  'data-bv-notempty' => 'true', 'data-bv-notempty-message' =>  "Size is required" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

  <%= submit_tag 'Submit', class: 'save_button btn btn-primary' %>
</div>
<% end %>

app/views/simulations/_graph.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <i class="fa fa-bar-chart-o fa-fw"></i> Graph
      </div>
      <div class="panel-body">
        <div id='chart'></div>
      </div>
    </div>
  </div>
</div>

app/views/simulations/_summary.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <i class="fa fa-bar-chart-o fa-fw"></i>Summary
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="summary row">
          <div class='row'>
            <div class='col-md-2'><span class='bold'>No. of races</span></div>
            <div class='col-md-2 totalRaces'></div>
            <div class='col-md-2'><span class='bold'>Winning races</span></div>
            <div class='col-md-2 winningRaces'></div>
            <div class='col-md-2'><span class='bold'>Winning Percentage</span></div>
            <div class='col-md-2 winningPercentage'></div>
          </div>
          <div class='row'>
            <div class='col-md-2'><span class='bold'>Profit/Loss</span></div>
            <div class='col-md-2 profitLoss'></div>
            <div class='col-md-2'><span class='bold'>Highest Amount</span></div>
            <div class='col-md-2 highestValue'></div>
            <div class='col-md-2'><span class='bold'>Lowest Amount</span></div>
            <div class='col-md-2 lowestValue'></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/simulations/new.html.erb
<div id="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header">Simulation</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <i class="fa fa-bar-chart-o fa-fw"></i> Scenarios
        </div>
        <div class="panel-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>

  <div id='summary'></div>
  <div id='graph'></div>
  <div id='details'></div>
  <div id="loadingOverlay" class="loadingOverlay" style="display:none">
    <img src="/assets/ajax_loader.gif" id="spinner" class='centered'/>
  </div>
</div>